// <auto-generated />
namespace TwitterProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ApplyChanges01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApplyChanges01));
        
        string IMigrationMetadata.Id
        {
            get { return "201612012350007_Apply Changes 01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
